/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gnome.adw.Application
import org.gnome.adw.ApplicationWindow
import org.gnome.adw.HeaderBar
import org.gnome.gio.ApplicationFlags
import org.gnome.gtk.Box
import org.gnome.gtk.Label
import org.gnome.gtk.Orientation
import org.example.audio.AudioEngine

class App {
    private val audioEngine = AudioEngine()

    fun start() {
        audioEngine.start()
    }

    fun getAudioStatus() = audioEngine.getStatus()
}

fun main(args: Array<String>) {
    val appInstance = App()
    val app = Application("org.example.ampsim", ApplicationFlags.DEFAULT_FLAGS)

    app.onActivate {
        appInstance.start()
        val status = appInstance.getAudioStatus()

        val headerBar = HeaderBar()

        val content = Box(Orientation.VERTICAL, 12)
        content.append(headerBar)
        
        val statusLabel = Label(if (status.isConnected) {
            "JACK Connected: ${status.sampleRate}Hz, ${status.bufferSize} samples"
        } else {
            "JACK Disconnected: ${status.lastError ?: "Unknown error"}"
        })
        content.append(statusLabel)

        val window = ApplicationWindow(app)
        window.setTitle("Amp Simulator")
        window.setDefaultSize(800, 600)
        window.setContent(content)
        window.present()
    }

    app.run(args)
}
