/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gnome.adw.Application
import org.gnome.adw.ApplicationWindow
import org.gnome.adw.HeaderBar
import org.gnome.gio.ApplicationFlags
import org.gnome.gtk.Box
import org.gnome.gtk.Label
import org.gnome.gtk.Orientation

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>) {
    val app = Application("org.example.ampsim", ApplicationFlags.DEFAULT_FLAGS)

    app.onActivate {
        val headerBar = HeaderBar()

        val content = Box(Orientation.VERTICAL, 12)
        content.append(headerBar)
        content.append(Label("Hello, World!"))

        val window = ApplicationWindow(app)
        window.setTitle("Amp Simulator")
        window.setDefaultSize(800, 600)
        window.setContent(content)
        window.present()
    }

    app.run(args)
}
