/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.5.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    kotlin("plugin.serialization") version "2.4.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // GTK4/libadwaita Java-GI bindings.
    implementation("org.java-gi:gtk:1.0.0-RC1")
    implementation("org.java-gi:adw:1.0.0-RC1")

    // JACK audio library integration.
    implementation(libs.jnajack)

    // Kotlin extensions
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.AppKt"
    applicationDefaultJvmArgs = listOf("--enable-native-access=ALL-UNNAMED")
}

// Compiles Blueprint -> UI -> GResource
tasks.register<Exec>("compileBlueprint") {
    workingDir = project.projectDir.resolve("src/main/resources")
    commandLine("blueprint-compiler", "compile", "gtk/mainwindow.blp", "--output", "mainwindow.ui")
}

tasks.register<Exec>("compileResources") {
    dependsOn("compileBlueprint")
    workingDir = project.projectDir.resolve("src/main/resources")
    commandLine("glib-compile-resources", "--target=ampsim.gresource", "--sourcedir=.", "resources.xml")
}

tasks.named("compileKotlin") {
    dependsOn("compileResources")
}

tasks.named<JavaExec>("run") {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

tasks.withType(JavaExec::class) {
    jvmArgs("--enable-native-access=ALL-UNNAMED")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
