/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appCanBeInstantiated() {
        val classUnderTest = App()
        assertNotNull(classUnderTest, "app should be instantiatable")
    }
}
